/*
 * This Java source file was generated by the Gradle 'init' task.
 */

/*
 *  @AUTHOR DINAR ABDUL HOLLIK FIRDAUS
 */
package UTS;
import java.util.Scanner;
public class App {
    public static void main(String[] args) {
        Scanner input = new Scanner (System.in);
        String nama, npm, message ;
        char grade ;  
        int n_akhir;
        long nilai ;
        while (true){
            System.out.print("Masukan nama : ");
            nama = input.nextLine();
            System.out.print("Masukan NPM (2155XXXXXXX) : ");
            npm = input.nextLine();
            nilai = Long.parseLong(npm);
            n_akhir =   (int)(nilai%100);
            if(n_akhir >= 80){
                grade = '\0';
                if (n_akhir >= 90 && n_akhir <=100){
                    grade = 'A';
                }
                else if (n_akhir >= 80 && n_akhir < 90){
                    grade = 'B';
                }
                 System.out.println("\n"+nama+" dengan NIM "+npm+" memiliki nilai akhir "+n_akhir+" = ("+grade+")"+""
                        + "\n dan dinyatakan Lulus");
                 break;
            }else{
                grade = '\0';
                if (n_akhir > 60 && n_akhir < 80){
                    grade = 'C';
                    message = "Lulus ala kadarnya";
                }
                else if (n_akhir >= 40 && n_akhir < 60){
                    grade = 'D';
                    message = "Nilai Anda Perlu Diperbaiki";
                }
                else {
                    grade = 'E';
                    message = "Tidak Lulus";
                }
                System.out.println("\n"+nama+" dengan NIM "+npm+" memiliki nilai akhir "+n_akhir+" = ("+grade+")"+"" + "\n dan dinyatakan  ("+message+") Coba Inputkan Nilai kembali \n");        
            }
        }
    }
}
